// Generated by scripts/optimize_assets.py; original files remain untouched.
export type OptimizedImage = {
  src: string;
  srcSet?: string;
  width?: number;
  height?: number;
};

const optimizedImages: Record<string, OptimizedImage> = {
  "/images/corporate-business.jpeg": {
    "src": "/images/optimized/corporate-business-480.webp",
    "srcSet": "/images/optimized/corporate-business-480.webp 480w, /images/optimized/corporate-business-800.webp 800w",
    "width": 848,
    "height": 1264
  },
  "/images/family-personal-law.jpeg": {
    "src": "/images/optimized/family-personal-law-480.webp",
    "srcSet": "/images/optimized/family-personal-law-480.webp 480w, /images/optimized/family-personal-law-800.webp 800w",
    "width": 848,
    "height": 1264
  },
  "/images/property-legal-consultation.jpeg": {
    "src": "/images/optimized/property-legal-consultation-480.webp",
    "srcSet": "/images/optimized/property-legal-consultation-480.webp 480w, /images/optimized/property-legal-consultation-800.webp 800w",
    "width": 848,
    "height": 1264
  },
  "/images/criminal-defense.jpeg": {
    "src": "/images/optimized/criminal-defense-480.webp",
    "srcSet": "/images/optimized/criminal-defense-480.webp 480w, /images/optimized/criminal-defense-800.webp 800w",
    "width": 848,
    "height": 1264
  },
  "/images/dispute-resolution.jpeg": {
    "src": "/images/optimized/dispute-resolution-480.webp",
    "srcSet": "/images/optimized/dispute-resolution-480.webp 480w, /images/optimized/dispute-resolution-800.webp 800w",
    "width": 848,
    "height": 1264
  },
  "/images/intellectual-property.jpeg": {
    "src": "/images/optimized/intellectual-property-480.webp",
    "srcSet": "/images/optimized/intellectual-property-480.webp 480w, /images/optimized/intellectual-property-800.webp 800w",
    "width": 848,
    "height": 1264
  },
  "/images/labor-employment.jpeg": {
    "src": "/images/optimized/labor-employment-480.webp",
    "srcSet": "/images/optimized/labor-employment-480.webp 480w, /images/optimized/labor-employment-800.webp 800w",
    "width": 848,
    "height": 1264
  },
  "/images/immigration.jpeg": {
    "src": "/images/optimized/immigration-480.webp",
    "srcSet": "/images/optimized/immigration-480.webp 480w, /images/optimized/immigration-800.webp 800w",
    "width": 848,
    "height": 1264
  },
  "/images/app-screens/categories.png": {
    "src": "/images/optimized/phone-categories-640.webp",
    "srcSet": "/images/optimized/phone-categories-360.webp 360w, /images/optimized/phone-categories-640.webp 640w, /images/optimized/phone-categories-960.webp 960w",
    "width": 1125,
    "height": 2778
  },
  "/images/app-screens/service-summary.png": {
    "src": "/images/optimized/phone-service-summary-640.webp",
    "srcSet": "/images/optimized/phone-service-summary-360.webp 360w, /images/optimized/phone-service-summary-640.webp 640w, /images/optimized/phone-service-summary-960.webp 960w",
    "width": 1500,
    "height": 3248
  },
  "/images/app-screens/call-connecting.png": {
    "src": "/images/optimized/phone-call-connecting-640.webp",
    "srcSet": "/images/optimized/phone-call-connecting-360.webp 360w, /images/optimized/phone-call-connecting-640.webp 640w, /images/optimized/phone-call-connecting-960.webp 960w",
    "width": 1500,
    "height": 3248
  },
  "/images/app-screens/service-progress-files.png": {
    "src": "/images/optimized/phone-service-progress-files-640.webp",
    "srcSet": "/images/optimized/phone-service-progress-files-360.webp 360w, /images/optimized/phone-service-progress-files-640.webp 640w, /images/optimized/phone-service-progress-files-960.webp 960w",
    "width": 1500,
    "height": 3248
  },
  "/images/app-screens/service-progress.png": {
    "src": "/images/optimized/phone-service-progress-640.webp",
    "srcSet": "/images/optimized/phone-service-progress-360.webp 360w, /images/optimized/phone-service-progress-640.webp 640w, /images/optimized/phone-service-progress-960.webp 960w",
    "width": 1500,
    "height": 3248
  },
  "/Somadhan ELT.svg": {
    "src": "/images/optimized/somadhan-elt-480.webp",
    "srcSet": "/images/optimized/somadhan-elt-480.webp 480w, /images/optimized/somadhan-elt-960.webp 960w",
    "width": 8509,
    "height": 1313
  },
  "/Somadhan BLT.svg": {
    "src": "/images/optimized/somadhan-blt-480.webp",
    "srcSet": "/images/optimized/somadhan-blt-480.webp 480w, /images/optimized/somadhan-blt-960.webp 960w",
    "width": 8067,
    "height": 1650
  },
  "/Somadhan ELW.svg": {
    "src": "/Somadhan ELW.svg",
    "width": 2042,
    "height": 315
  },
  "/Somadhan BLW.svg": {
    "src": "/Somadhan BLW.svg",
    "width": 1936,
    "height": 396
  }
};

export function getOptimizedImage(originalSrc: string): OptimizedImage {
  return Object.prototype.hasOwnProperty.call(optimizedImages, originalSrc)
    ? optimizedImages[originalSrc]
    : { src: originalSrc };
}
